{
 "title": "SPOTLITE",
 "description": "WORDPRESS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "[DEBUG_SPOT_LITE]",
   "type": "logs",
   "description": "Wordpress logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"wordpress\"} |= `[DEBUG_SPOT_LITE]`"
    }
   ]
  },
  {
   "title": "GENERAL LOGS",
   "type": "logs",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"wordpress\"} != `other_vhosts_access.log` != `Unable to open logs`"
    }
   ]
  },
  {
   "title": "APACHE LOGS",
   "type": "logs",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"wordpress\"} |= `apache2`"
    }
   ]
  }
 ]
}